[build]
  command = "yarn build"
  publish = "webapp"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self'"

[[headers]]
  for = "/config.*.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/i18n/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/home/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/sites/*"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"